version: '3'
services:
  scg_app:
    build: .
    container_name: scg_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    restart: always
  database:
    image: mysql:5.7
    container_name: scg_database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scg_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    restart: always
