<h1 class="h3 mb-2 text-gray-800">Restaurants</h1>
<p class="mb-4">Place search | Place API (by Google)</p>
<div class="row">
    <div class="col-sm-12">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Bangsue Area</h6>
            </div>
            <div class="card-body">
                <?php foreach(array_chunk($this->restaurants, 2) as $restaurants ) { ?>
                <div class="row mb-4">
                    <?php foreach($restaurants as $restaurant) { ?>
                    <?php /* ?>
                    <restaurants-component restaurants="<?= htmlspecialchars(json_encode($restaurant), ENT_QUOTES, 'UTF-8')?>" key="<?= $key;?>"></restaurants-component>
                    <?php */ ?>
                    <div class="col-xs-12 col-sm-6">
                        <div class="card border-left-primary shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="media">
                                            <img src="https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference=<?= $restaurant->photos[0]->photo_reference;?>&key=<?=$this->key;?>" class="mr-3" alt="<?= $restaurant->name;?>" width="100">
                                            <div class="media-body">
                                                <div class="font-weight-bold text-primary text-uppercase mb-1"><?= $restaurant->name;?></div>
                                                <div class="text-xs mb-0 font-weight-bold text-gray-800"><?= $restaurant->vicinity;?></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-auto">
                                        <a href="https://maps.google.com/?q=<?= $restaurant->geometry->location->lat;?>,<?= $restaurant->geometry->location->lng;?>" target="_blank"><i class="fas fa-map-marker-alt fa-2x text-gray-300"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>