<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet('https://fonts.googleapis.com/css?family=Sarabun')
            ->prependStylesheet($this->basePath('assets/css/app.css'))
        ?>

    </head>
    <body>
        <div id="wrapper">
            <!--<sidebar-component></sidebar-component>-->
            <body-component content="<?= htmlspecialchars($this->content);?>"></body-component>
        </div>
        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('assets/js/app.js'))
            ->prependFile($this->basePath('assets/js/vendor.js'))
            ->prependFile($this->basePath('assets/js/manifest.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
        ?>
    </body>
</html>
